Fix autocomplete input debounce
lab900/angular-libraries pull request #103
Opened 2021-05-21 15:11 UTC by lab900-winand-vandenbergh

2021-05-21 15:15 UTC, lab900-senn-lambrecht requested changes

2021-05-21 15:15 UTC, lab900-senn-lambrecht commented on projects/forms/src/lib/components/form-fields/autocomplete-field/autocomplete-field.component.ts
> +import { Observable, isObservable, of, fromEvent, Subject, BehaviorSubject } from 'rxjs';
subject unused?

2021-05-21 15:15 UTC, lab900-senn-lambrecht commented on projects/forms/src/lib/components/form-fields/autocomplete-field/autocomplete-field.component.ts
> +    this.inputChange.next(($event.target as any).value);
as string

2021-05-21 15:15 UTC, lab900-senn-lambrecht commented on projects/forms/src/lib/components/form-fields/autocomplete-multiple-field/autocomplete-multiple-field.component.ts
> +    this.inputChange.next(($event.target as any).value);
as string

2021-05-21 15:15 UTC, lab900-senn-lambrecht commented on projects/forms/src/lib/components/form-fields/autocomplete-field/autocomplete-field.component.html
> +        (input)="this.inputChanged($event)"
remove this.

2021-05-21 15:26 UTC, lab900-winand-vandenbergh commented on projects/forms/src/lib/components/form-fields/autocomplete-multiple-field/autocomplete-multiple-field.component.ts
> +    this.inputChange.next(($event.target as any).value);
it's the value that's a string, not the target. I'm not sure how to type the target. I think this any typing is code you wrote as well :p

2021-05-21 15:27 UTC, lab900-winand-vandenbergh commented on projects/forms/src/lib/components/form-fields/autocomplete-field/autocomplete-field.component.html
> +        (input)="this.inputChanged($event)"
why? this is being used to set the subject.

2021-05-31 08:44 UTC, lab900-senn-lambrecht commented on projects/forms/src/lib/components/form-fields/autocomplete-field/autocomplete-field.component.html
> +        (input)="this.inputChanged($event)"
I meant just the "this." the this context isn't needed.

2021-05-31 08:50 UTC, lab900-senn-lambrecht approved these changes

2021-05-31 08:51 UTC, lab900-winand-vandenbergh commented on projects/forms/src/lib/components/form-fields/autocomplete-field/autocomplete-field.component.ts
> +    this.inputChange.next(($event.target as any).value);
only the value of the $event.target is a string. I don't know how the $event.target should be typed. This was already typed as any by you.

2021-05-31 11:36 UTC, merged