Admin-form-popup
lab900/angular-libraries pull request #11
Opened 2020-09-11 16:12 UTC by Lab900-Joshua-Brughmans

2020-09-11 20:14 UTC, lab900-johan-cosemans commented on projects/admin/src/lib/components/translatable-form-dialog/translatable-form-dialog.component.html
> +    <div class="language-select-container" *ngIf="dialogAdminSchemaData.schema.languages">
Dit zou je beter in een aparte component zetten (lab900-translatable-form-container?) zodat je het flexibeler kan gebruiken. Nu doet deze component twee dingen: de taalselectie toevoegen en alles tonen in een dialoog

2020-09-11 20:16 UTC, lab900-johan-cosemans commented on projects/admin/src/lib/components/translatable-form-dialog/translatable-form-dialog.component.ts
> +    this.currentLanguage = Array.from(this.dialogAdminSchemaData.schema.languages.keys())[0];
ben je verplicht om een taal in te geven? Op deze manier kunnen we admin module niet meer gebruiken als we geen vertalingen nodig hebben

2020-09-11 20:18 UTC, lab900-johan-cosemans commented on projects/admin/src/lib/components/translatable-form-dialog/translatable-form-dialog.component.ts
> +          const translatables = {};
Wat gebeurt er hier? Bij een error doe je vanalles dat niets te maken lijkt te hebben met de error #confused

2020-09-11 20:19 UTC, lab900-johan-cosemans commented on projects/admin/src/lib/components/translatable-form-dialog/translatable-form-dialog.component.ts
> +          const translatables = {};
Volgorde: Then, Catch, Finally

2020-09-11 20:25 UTC, lab900-johan-cosemans commented on projects/admin/src/lib/models/schema.ts
> +    schema.fields
is het niet een stuk korter om na de originele .map() een sort te doen op translatable?

2020-09-11 20:26 UTC, lab900-johan-cosemans commented on projects/admin/src/lib/models/schemaField.ts
> +  translatable: boolean;
Hoeft niet verplicht te zijn - default is false

2020-09-11 20:28 UTC, lab900-johan-cosemans commented on projects/admin/src/lib/pages/admin-page/admin-page.component.ts
> +    this.loading = false;
omringen in try/(catch)/finally - anders wordt loading nooit op false gezet als er iets misloopt

2020-09-11 20:30 UTC, lab900-johan-cosemans commented on src/app/modules/showcase-admin/examples/admin-page/admin-page-example.component.ts
> +      return {
iets realistischer als je er ook een setTimeout rond zet zoals in update (zo kan je de loading events ook zien in de showcase)

2020-09-11 20:31 UTC, lab900-johan-cosemans commented on src/app/modules/showcase-admin/examples/admin-page/admin-page-example.component.ts
> +        id: '2',
NEWS_ITEMS in de config heeft alle demo data, niet nodig om dit hier ook te kopieren

2020-09-11 20:35 UTC, lab900-johan-cosemans commented
![image](https://user-images.githubusercontent.com/43887527/92970488-0c250c80-f47f-11ea-88cf-1d3a18c55fde.png)

2020-09-11 20:39 UTC, lab900-johan-cosemans commented
bug: 
Attributes "title" and "subtitle" are also available in the root of the object (and also in the translations)

![image](https://user-images.githubusercontent.com/43887527/92970795-8d7c9f00-f47f-11ea-8100-5b910c39bae8.png)

2020-09-18 11:31 UTC, lab900 commented on projects/admin/src/lib/components/translatable-form-dialog/translatable-form-dialog.component.ts
> +        this.formData = {}; // Necessary to re-render the form
Error tonen

2020-09-22 06:51 UTC, lab900-senn-lambrecht requested changes

2020-09-22 06:51 UTC, lab900-senn-lambrecht commented on projects/admin/src/lib/components/translatable-admin-table/translatable-admin-table.component.scss
> +        min-width: 40px;
gewoon width gebruiken?

2020-09-22 06:51 UTC, lab900-senn-lambrecht commented on projects/admin/src/lib/components/translatable-admin-table/translatable-admin-table.component.scss
> +        min-width: 40px;
gewoon width gebruiken?

2020-09-22 06:51 UTC, lab900-senn-lambrecht commented on projects/admin/src/lib/components/translatable-admin-table/translatable-admin-table.component.scss
> +  mat-header-cell:first-of-type {
kan samen met de vorige selector:
`mat-cell:first-of-type, mat-header-cell:first-of-type { ... }`

2020-09-22 06:51 UTC, lab900-senn-lambrecht commented on projects/admin/src/lib/components/translatable-admin-table/translatable-admin-table.component.scss
> +      background-color: #f5f5f5;
Kleur in variable

2020-09-22 06:51 UTC, lab900-senn-lambrecht commented on projects/admin/src/lib/components/translatable-admin-table/translatable-admin-table.component.html
> +                   [disabled]="loading || !data || !data?.items"
kan korter: `loading || !data?.items`

2020-09-22 06:51 UTC, lab900-senn-lambrecht commented on projects/admin/src/lib/components/translatable-admin-table/translatable-admin-table.component.html
> +                   [length]="(data && data?.items) ? (data.hasMore ? page * data.items.length + 1 : page * data.items.length) : 0">
Ik zou deze waarde berekening in een getter steken.

2020-09-22 06:51 UTC, lab900-senn-lambrecht commented on projects/admin/src/lib/components/translatable-form-dialog/translatable-form-dialog.component.html
> +    <button mat-raised-button mat-dialog-close tabindex="-1">Cancel</button>
Cancel als translation toevoegen

2020-09-22 06:51 UTC, lab900-senn-lambrecht commented on projects/admin/src/lib/components/translatable-form-dialog/translatable-form-dialog.component.html
> +            Clear current language
Clear current language als translation toevoegen

2020-09-22 06:51 UTC, lab900-senn-lambrecht commented on projects/admin/src/lib/components/translatable-form-dialog/translatable-form-dialog.component.html
> +    <button mat-raised-button color="primary" [disabled]="(!lab900Form.valid || loading || !!error)" (click)="submit(lab900Form.value)" tabindex="1">Ok</button>
Ok als translation toevoegen

2020-09-22 06:51 UTC, lab900-senn-lambrecht commented on projects/admin/src/lib/components/translatable-form-dialog/translatable-form-dialog.component.scss
> +
verwijdere lege rij. Heb je een linter voor de frontend?

2020-09-22 06:51 UTC, lab900-senn-lambrecht commented on projects/admin/src/lib/directives/translatable-form-dialog.directive.ts
> +    dialog.beforeClosed().subscribe((data) => {});
unsubscribe

2020-09-22 06:51 UTC, lab900-senn-lambrecht commented on projects/admin/src/lib/models/schema.ts
> +        });
geen object mappen naar een andere object met exact dezelfde properties. 
Enkel de options prop afchecken.

2020-09-22 06:51 UTC, lab900-senn-lambrecht commented on projects/admin/src/lib/pages/admin-page/admin-page.component.html
> +        <button *ngIf="schema.creatable" mat-raised-button color="primary" lab900FormDialog [schema]="schema" [submitFormHandler]="createHandler">Create</button>
Create als translation

2020-09-22 06:51 UTC, lab900-senn-lambrecht commented on projects/admin/src/lib/pages/translatable-admin-page/translatable-admin-page.component.html
> +        <button *ngIf="schema.creatable" mat-raised-button color="primary" lab900TranslatableFormDialog [schema]="schema" [submitFormHandler]="createHandler" [create]="true" [getHandler]="getHandler"
Create als translation

2020-09-22 06:51 UTC, lab900-senn-lambrecht commented on src/app/modules/showcase-admin/examples/admin-page/admin-page-example.component.ts
> +      console.log(object);
console.logs verwijderen

2020-09-22 06:51 UTC, lab900-senn-lambrecht commented on src/app/modules/showcase-admin/examples/admin-page/admin-page-example.component.ts
> +    defaultPageSize(): number {
kan dit geen property zijn ipv een method?

2020-09-22 06:51 UTC, lab900-senn-lambrecht commented on src/app/modules/showcase-admin/examples/admin-page/admin-page-example.component.ts
> +      console.log(item);
verwijder console.log

2020-09-22 06:51 UTC, lab900-senn-lambrecht commented on src/app/modules/showcase-admin/examples/translatable-admin-page/translatable-admin-page-example.component.ts
> +      console.log(item);
verwijder console.log

2020-09-22 06:51 UTC, lab900-senn-lambrecht commented on src/app/modules/showcase-admin/examples/translatable-admin-page/translatable-admin-page-example.component.ts
> +}
verwijdere lege constructor + ngOnInit

2020-09-22 06:51 UTC, lab900-senn-lambrecht commented on src/app/modules/showcase-admin/examples/translatable-admin-page/translatable-admin-page-example.component.ts
> +      console.log(object);
Console.logs verwijderen

2020-09-22 06:51 UTC, lab900-senn-lambrecht commented on src/app/modules/showcase-admin/examples/admin-page/admin-page-example.component.ts
> +  ngOnInit(): void {}
lege constructor + ngOnINit verwijderen

2020-09-22 06:51 UTC, lab900-senn-lambrecht commented on src/app/modules/showcase-admin/examples/translatable-admin-page/translatable-admin-page-example.component.ts
> +      return 3;
prop ipv method?

2020-09-22 07:26 UTC, Lab900-Joshua-Brughmans commented on src/app/modules/showcase-admin/examples/admin-page/admin-page-example.component.ts
> +    defaultPageSize(): number {
@lab900-senn-lambrecht dit is code van de eerste iteratie van de libraries, die we opnieuw hebben gekopieerd voor de demo page, dus ben niet 100% zeker, maar dit is een functie die geimplementeerd moet worden in DataService. Ik vermoed dat Johan hier een functie van heeft gemaakt, aangezien dit niet in elke implementatie per se een statische waarde moet zijn.

2020-09-23 05:56 UTC, lab900-senn-lambrecht approved these changes

2020-09-23 05:56 UTC, merged