Add fetching authorized images and image overlay
lab900/angular-libraries pull request #88
Opened 2021-03-25 14:14 UTC by lab900-winand-vandenbergh

2021-03-25 14:30 UTC, lab900-senn-lambrecht requested changes

2021-03-25 14:30 UTC, lab900-senn-lambrecht commented on projects/forms/src/lib/components/image-preview-modal/image-preview-modal.component.ts
> +  public ngOnInit(): void {}
remove

2021-03-25 14:30 UTC, lab900-senn-lambrecht commented on projects/forms/src/lib/components/image-preview-modal/image-preview-modal.component.ts
> +      .catch((e) => console.error(e));
moet ge dit niet visueel tonen?

2021-03-25 14:30 UTC, lab900-senn-lambrecht commented on projects/forms/src/lib/forms.module.ts
> +    AuthImagePipe,
2x

2021-03-25 14:30 UTC, lab900-senn-lambrecht commented on projects/forms/src/lib/forms.module.ts
> +        AuthImagePipe,
Moet hier niet staan?

2021-03-25 14:30 UTC, lab900-senn-lambrecht commented on projects/forms/src/lib/components/form-fields/file-preview-field/file-preview-field.component.html
> +            {{options.overlay.text}}
translate pipe toevoegen

2021-03-25 14:47 UTC, lab900-winand-vandenbergh commented on projects/forms/src/lib/forms.module.ts
> +        AuthImagePipe,
Jawel, want ik gebruik die pipe ook in een ts file van een component en dan moet die wel bij providers staan.

2021-03-25 15:26 UTC, lab900-senn-lambrecht commented on projects/forms/src/lib/forms.module.ts
> +        AuthImagePipe,
Ah je gebruikt dat als injectable. Dat is niet echt de bedoeling van een pipe. 
Beter een directive van maken. Ik zal u een voorbeeld sturen dat we ook in Huapii gebruiken

2021-03-29 16:27 UTC, lab900-winand-vandenbergh commented on projects/forms/src/lib/forms.module.ts
> +        AuthImagePipe,
@lab900-senn-lambrecht Kunt ge daar nog een voorbeeld van geven?

2021-03-30 14:43 UTC, lab900-senn-lambrecht approved these changes

2021-03-30 14:46 UTC, merged